language: ruby
rvm:
  - 2.2.3
env:
  - TRAVIS_NODE_VERSION="6"
before_install:
    - gem install sass
    - gem install scss-lint
    - npm install -g grunt-cli 
install: npm install
before_script: 
    - grunt theme