language: node_js
node_js:
    - 6
before_install:
    - gem install sass
    - gem install scss-lint
    - npm install -g grunt-cli 
install: 
    - npm install
before_script: 
    - grunt theme
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8